# For more details and explanations see:
# https://github.com/google-github-actions/setup-gcloud/tree/master/example-workflows/cloud-run

# Copyright 2019 Google, LLC.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

on:
  push:
    paths:
      - ".github/workflows/build-and-deploy-landing_page.yaml"
      - "demo_data/**"
      - "landing_page/**"
    branches:
      - "main"

name: Build and Deploy landing page to Cloud Run
env:
  SERVICE: ioxio-tags-landing-page
  REGION: europe-west1
  REGISTRY: eu.gcr.io
  DOCKER_BUILDKIT: 1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Authorize Docker push
        run: gcloud auth configure-docker

      - name: Build and Push
        run: |-
          cp -r demo_data/.well-known landing_page/static
          cd landing_page
          docker build -t ${{ env.REGISTRY }}/${{ secrets.GCP_PROJECT }}/${{ env.SERVICE }}:${{ github.sha }} .
          docker push ${{ env.REGISTRY }}/${{ secrets.GCP_PROJECT }}/${{ env.SERVICE }}:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |-
          gcloud run deploy ${{ env.SERVICE }} \
            --region ${{ env.REGION }} \
            --image ${{ env.REGISTRY }}/${{ secrets.GCP_PROJECT }}/${{ env.SERVICE }}:${{ github.sha }} \
            --platform "managed" \
            --quiet \
            --allow-unauthenticated
